import { Todo } from "./todo";

export const TODOS: Todo [] = [
    {
        id: 1,
        title: "Peindre le mur",
        content: "Content todo 1",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 2,
        title: "Acheter du lait",
        content: "Content todo 3",
        author: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 3,
        title: "Faire les devoirs",
        content: "Content todo 3",
        author: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 4,
        title: "Sauver l'univers",
        content: "Content todo 4",
        author: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 5,
        title: "Allumer son pc",
        content: "Content todo 5",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 6,
        title: "Dormir",
        content: "Content todo 6",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 7,
        title: "Acheter une orange",
        content: "Content todo 7",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 8,
        title: "Faire du sport",
        content: "Content todo 8",
        author: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 9,
        title: "Faire son tp",
        content: "Content todo 9",
        author: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 10,
        title: "Faire quelque chose",
        content: "Content todo 10",
        author: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    
]