import { Book } from "./book"
import { Categories } from "./categories"
import { CATEGORIES } from "./mock-categories"
import { USERS } from "./mock-users"
import { Users } from "./users"


export const BOOKS: Book [] = [
    {
        id: 1,
        title: "Le tour du monde en quatre-vingts jours",
        resume: "Phileas Fogg est un gentleman riche vivant une vie solitaire à Londres...",
        image: "Book1.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 2,
        title: "Solo leveling",
        resume: "Dix ans auparavant, des portails ont commencé à apparaître un peu partout dans le monde...",
        image: "Book2.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 3,
        title: "Les Misérables",
        resume: "L'action se déroule en France au cours du premier tiers du xixe siècle...",
        image: "Book3.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 4,
        title: "Le Seigneur des Anneaux",
        resume: "Après un prologue décrivant les Hobbits et leurs mœurs, le passé de la Terre du Milieu et un rapide résumé des aventures de Bilbon Sacquet...",
        image: "Book4.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 5,
        title: "One piece",
        resume: "l'aventure du futur roi des pirates...",
        image: "Book5.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 6,
        title: "Mon premier livre",
        resume: "Mon tout premier livre",
        image: "Book6.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 7,
        title: "Tokyo ghoul",
        resume: "Dans la ville de Tokyo, des créatures nommées goules sont apparues...",
        image: "Book7.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 8,
        title: "Notre-Dame de Paris",
        resume: "L'intrigue se déroule à Paris en 1482...",
        image: "Book8.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 9,
        title: "Mon autobiographie",
        resume: "Je tente d'écrire ce que j'ai vécu",
        image: "Book9.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
    {
        id: 10,
        title: "Le temps des tempêtes",
        resume: "...",
        image: "Book10.png",
        createdAt: new Date(),
        updatedAt: null,
        categorie: [CATEGORIES[1]],
        auteur: USERS[1],
    },
]