import { Book } from "./book"

export const BOOKS: Book [] = [
    {
        id: 1,
        title: "Le tour du monde en quatre-vingts jours",
        resume: "Phileas Fogg est un gentleman riche vivant une vie solitaire à Londres...",
        image: "Book1.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [1, 2, 3],
        auteurId: 1,
    },
    {
        id: 2,
        title: "Solo leveling",
        resume: "Dix ans auparavant, des portails ont commencé à apparaître un peu partout dans le monde...",
        image: "Book2.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 3,
        title: "Les croustillons",
        resume: "Une histoire de mixmax entre autres",
        image: "Book3.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 4,
        title: "Le Seigneur des Anneaux",
        resume: "Après un prologue décrivant les Hobbits et leurs mœurs, le passé de la Terre du Milieu et un rapide résumé des aventures de Bilbon Sacquet...",
        image: "https://m.media-amazon.com/images/I/711wTudJGtL._AC_UF1000,1000_QL80_.jpg",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 5,
        title: "One piece",
        resume: "l'aventure du futur roi des pirates...",
        image: "Book5.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 6,
        title: "Mon premier livre",
        resume: "Mon tout premier livre",
        image: "Book6.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 7,
        title: "Tokyo ghoul",
        resume: "Dans la ville de Tokyo, des créatures nommées goules sont apparues...",
        image: "Book7.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 8,
        title: "Notre-Dame de Paris",
        resume: "L'intrigue se déroule à Paris en 1482...",
        image: "Book8.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 1,
    },
    {
        id: 9,
        title: "Mon autobiographie",
        resume: "Je tente d'écrire ce que j'ai vécu",
        image: "Book9.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 3,
    },
    {
        id: 10,
        title: "Le temps des tempêtes",
        resume: "...",
        image: "Book10.png",
        createdAt: new Date(),
        updatedAt: null,
        categorieId: [2],
        auteurId: 3,
    },
]